# -*- coding: utf-8 -*-

DEBUG = True

WTF_CSRF_ENABLED = False

SECRET_KEY = '!@#$%8F6F98EC3684AECA1DC44E1CB816E4A5^&*()'

UPLOAD_FOLDER = '/tmp/PCAP/'
FILE_FOLDER = '/tmp/Files/'
PDF_FOLDER = '/tmp/Files/PDF/'

# for toolbar
DEBUG_TB_PROFILER_ENABLED = True
DEBUG_TB_INTERCEPT_REDIRECTS = False
